### ISSUE TITLE
app crashes when course name edited

### ISSUE THREAD

**Issue by yolicap** [yolicap/CollegeScheduler#5]
just putting this here for now. not sure if issue can be replicated for other items. will investigate after we finish basic requirements

**Comment by yolicap** [comment]
`ATAL EXCEPTION: main
Process: com.example.collegescheduler, PID: 12765
java.lang.IllegalArgumentException: No enum constant java.time.DayOfWeek.SELECT DAYS
at java.lang.Enum.valueOf(Enum.java:302)
at java.time.DayOfWeek.valueOf(DayOfWeek.java:109)
at com.example.collegescheduler.ui.addCourse.AddCourse$4$2.lambda$onClick$0(AddCourse.java:270)
at com.example.collegescheduler.ui.addCourse.AddCourse$4$2$$ExternalSyntheticLambda0.accept(Unknown Source:4)
at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:606)
at com.example.collegescheduler.ui.addCourse.AddCourse$4$2.onClick(AddCourse.java:269)
at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
2024`

Here is the stack in case anyone wants to look at it
